services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Fab\Vidi\Command\VidiCommandController:
    tags:
      - name: 'console.command'
        command: 'vidi:analyseRelations'
        schedulable: false
